### ISSUE TITLE
[Feature]: Product image selection

### ISSUE THREAD

**Issue by whg517** [zncdatadev/trino-operator#120]
### Duplicates

I have searched the existing issues

### Summary 💡

Select an appropriate image and correct deployment logic based on the image tag design rules and compatibility with operator.

trace:

- [x] https://github.com/zncdatadev/zookeeper-operator/pull/88
- [x] https://github.com/zncdatadev/hdfs-operator/pull/89
- [x] https://github.com/zncdatadev/hive-operator/pull/120
- [x] https://github.com/zncdatadev/hbase-operator/pull/68
- [x] https://github.com/zncdatadev/spark-k8s-operator/pull/120
- [x] https://github.com/zncdatadev/superset-operator/pull/63
- [x] https://github.com/zncdatadev/dolphinscheduler-operator/pull/70
- [x] https://github.com/zncdatadev/trino-operator/pull/158
- [x] https://github.com/zncdatadev/kafka-operator/pull/75

### Examples 🌈

backgeound: Current kubedoop version is `0.1.0` and we have already adapted trino `450`, and `450` is recommonded for this version.

#### glance

```yaml
image:
    # custom: my.repo.company.org/trino:450    # when use custom repository, please set image with tag
    repo: quay.io/zncdatadev       # This is official image repository
    productVersion: 450          # The version is trino in image
    kubedoopVersion: 0.1.0                # This is kubedoop version
```

**CASE-1**

```yaml
# nothing
```

==

```yaml
image:
    repo: quay.io/zncdatadev
    productVersion: 450
    kubedoopVersion: 0.1.0
```

Use the official repository and the current kubedoop version, and select the best product version to compose the final image: `quay.io/zncdatadev/trino:450-kubedoop0.1.0`

**CASE-2**

```yaml
image:
    productVersion: 455
```

==

```yaml
image:
    repo: quay.io/zncdatadev
    productVersion: 455
    kubedoopVersion: 0.1.0
```

Using the official repository and the current kubedoop version, using the specified product version `455`, compose the final image: `quay.io/zncdatadev/trino:455-kubedoop0.1.0`

⚠️Note: If this image does not exists in the official repository, the service cannot be deployed successfully. If the current version of kubedoop `0.1.0` does not support the specified product version `455`, operator throws an exception and does not create the deployment resource.

**CASE-3**

```yaml
image:
    repo: my.repo.company.org/zncdatadev
```

==

```yaml
image:
    repo: my.repo.company.org/zncdatadev
    productVersion: 450
    kubedoopVersion: 0.1.0
```

If you proxy the official repository, you can specify your own repository using the repo. The image tag rules in the custom repository MUST be the same as those in the official repository, otherwise an Image cannot be found error may occur. Compose the final image: `my.repo.company.org/zncdatadev/trino:450-kubedoop0.1.0`

**CASE-4**

```yaml
image:
    custom: my.repo.company.org/trino:450
    productVersion: 450   # When use custom repository, productVersion is MUST be set
    # kubedoopVersion: 0.1.0       # In custom, this value will ignore
```

==

```yaml
image:
    custom: my.repo.company.org/trino:450
    productVersion: 450
```

With a custom Image, you must specify the product version in the Image to tell the operator what logic to use to deploy it. Compose the final image: `my.repo.company.org/trino:450`

⚠️Note: If no product version is specified when using a custom image, an exception is thrown and no resource is created.

**Other-CASE**

```yaml
image:
    kubedoopVersion: 0.1.0
```

If the final image `quay.io/zncdatadev/trino:450-kubedoop0.1.0` done not exist, the deployed resource will fail.

```yaml
image:
    custom: my.repo.company.org/trino:450
    productVersion: 455
```

The trino version `productVersion: 455` received by the operator does not match the trino version `my.repo.company.org/trino:450` in the customized image. As a result, the configurations created by the operator for the trino may be incorrect. So, unknown problems such as service exceptions or trino startup failures may occur.
