### ISSUE TITLE
[Feature]: Add logging collection by vector

### ISSUE THREAD

**Issue by whg517** [zncdatadev/trino-operator#152]
trace:

- [x] https://github.com/zncdatadev/zookeeper-operator/pull/100
- [x] https://github.com/zncdatadev/hdfs-operator/pull/79
- [x] https://github.com/zncdatadev/hive-operator/pull/131
- [x] https://github.com/zncdatadev/dolphinscheduler-operator/pull/71
- [x] https://github.com/zncdatadev/trino-operator/pull/158
- [x] https://github.com/zncdatadev/kafka-operator/pull/76
- [x] https://github.com/zncdatadev/hbase-operator/pull/86
- [x] https://github.com/zncdatadev/spark-k8s-operator/pull/126
- [x] https://github.com/zncdatadev/superset-operator/pull/81
